replicaCount: 1

image:
  repository: ghcr.io/janatmr/cloud-crafter/events
  tag: "08f92d765965f80fdfff5d10fa06e2d96582b662"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 128Mi

rollingUpdate:
  maxUnavailable: 25%
  maxSurge: 25%

env:
  - name: PORT
    value: "3000"
