apiVersion: v1
kind: Service
metadata:
  name: {{ include "events.name" . }}
  labels:
    {{- include "events.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "events.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
