replicaCount: 2

image:
  repository: ghcr.io/janatmr/cloud-crafter/notifications
  tag: "d562f0ee22e734f8b9c1228484fa64a63d330818"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 128Mi

rollingUpdate:
  maxUnavailable: 25%
  maxSurge: 25%

env:
  - name: PORT
    value: "3000"
