replicaCount: 2

image:
  repository: ghcr.io/janatmr/cloud-crafter/notifications
  tag: "d0ad3f5b8c45634de8fb2e1a27c1c1cf752a4afa"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 128Mi

rollingUpdate:
  maxUnavailable: 25%
  maxSurge: 25%

env:
  - name: PORT
    value: "3000"
