{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "notifications.name" . }}
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "notifications.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
